### ISSUE TITLE
The gem does not work with the latest versions of paperclip

### ISSUE THREAD

**Issue by rnaud** [jstorimer/delayed_paperclip#31]
Hello,

I was using the paperclip gem without any versioning, always updating, but it happens that the gem delayed paperclip is failing on latest versions of the paperclip gem.

I went up to ref "65e8d4f6de50732d8e1b", after this one, the delayed jobs keep looping, the log says that the job was completed but keeps doing it, over and over again.

Is this only happening to me ? Is there a way to have a more verbose log to check it ?
Things go back to normal if I remove the gem from my Gemfile, but obviously slower.

Thanks for your help !

**Comment by bigfleet** [comment]
@rnaud Are you having issues similar at all to #30?

**Comment by Bertg** [comment]
this seems similar to #30. I would suggest using the latest master version, or waiting until 0.7 gets released, which should be soon.

**Comment by rnaud** [comment]
Sorry, I didn't catch the #30 issue, yes this is exactly it, glad to know it's fixed in 0.7 :)

(I think the latest master version was not helping still, I was using github version, I just tried the gemcutter version to check if I was too "nightly"

**Comment by jstorimer** [comment]
Just released 0.7, should be fixed.

**Comment by rnaud** [comment]
Quick question though. The source on github doesn't show the 0.7 version, nor the 0.6.5 version for that matters. Is there another source I should be looking at ?

**Comment by Bertg** [comment]
i added the tags...

**Comment by rnaud** [comment]
The issue is not fixed for me in 0.7.1 with paperclip 2.3.15.
It's even kinda worse, the job is not added to Delayed::Job queue, the _processing column is set to nil. And I see nothing failing, no log anywhere.

**Comment by Bertg** [comment]
hmm, could you provide us with a code example (minimal rails app) or some test that show this happening?
I seem to have no issues here.

**Comment by rnaud** [comment]
Well my app is pretty big already, if there is a way to debug the gem from my actual app that would be better I guess.

Here is the paperclip related stuff in my model : 

  has_attached_file :file,
                    :url => ":s3_alias_url",
                    :s3_host_alias => Proc.new { |image| "#{image.bucket_name}" },
                                       :styles => { 
                                          :high => "500x500#",
                                              :large => "300x300#",
                                              :bigthumb => "100x100#",
                                              :thumb => "50x50#"
                                          },
                                      :convert_options => { :all => '-auto-orient -quality 70', :large => "-quality 30" },
                    :processors => [:rotator],
                                      :storage => :s3,
                    :default_url => "#{Onefeat::DOMAIN}/files/:style/missing.png",
                                      :s3_credentials => "#{Rails.root.to_s}/config/s3.yml",
                                      :path => "/:style/:id/:filename"

  process_in_background :file

**Comment by Bertg** [comment]
is this issue fixed for you, seeing ticket #32?

**Comment by rnaud** [comment]
Yes it is, for some reason I wasn't able to find back this issue in the github tracker, sorry to the double post.

**Comment by Bertg** [comment]
Np
